language: python
python:
  - "2.7"
env:
  - DJANGO=1.7.1
install:
  - pip install -q -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=protector setup.py test
after_success:
  coveralls
