language: python
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO=1.8.18
  - DJANGO=1.11.3
install:
  - pip install -q -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=protector setup.py test
after_success:
  coveralls
